export const FETCHING_COIN_DATA = 'FETCHING_COIN_DATA'
export const FETCH_COIN_DATA_SUCCESS = 'FETCH_COIN_DATA_SUCCESS'
export const FETCH_COIN_DATA_FAIL = 'FETCH_COIN_DATA_FAIL'

export const FETCHING_GLOBAL_COIN_DATA = 'FETCHING_GLOBAL_COIN_DATA'
export const FETCH_GLOBAL_COIN_DATA_SUCCESS = 'FETCH_GLOBAL_COIN_DATA_SUCCESS'
export const FETCH_GLOBAL_COIN_DATA_FAIL = 'FETCH_GLOBAL_COIN_DATA_FAIL'

export const SET_EMPTY_FAV_COIN_DATA = 'SET_EMPTY_FAV_COIN_DATA'
